#
# This file is part of LitePCIe.
#
# Copyright (c) 2024-2025 Enjoy-Digital <enjoy-digital.fr>
#
# SPDX-License-Identifier: BSD-2-Clause

# Use latticesemi.com_ip_pcie_x1_1.2.5 (module "pci", generated by Radiant IPGen with
# generator core "pci_ipgen_lscc_pcie_gen3"). This is a different Lattice IP than the
# one LFCPNXPCIEPHY wraps -- different device family (LFD2NX), different top-level
# module/port names (no "link0_" prefix; TX/RX TLP ports are named "vc_tx_*"/"vc_rx_*"),
# and this archive is only ever generated single-lane (module="pcie_x1", LINK_WIDTH="X1"):
# rxp_i/txp_o/refret_i/rext_i are all scalar ports, not per-lane buses -- there's no
# "nlanes" to configure.
#
# Unlike LFCPNXPCIEPHY's IP, this one's .cfg has "USE_DEFAULT_IF": true and bakes vendor/
# device ID, BAR sizing, and MSI capability (MSI enabled, MSI-X disabled) directly into
# synthesis-time Verilog parameters instead of requiring a boot-time LMMI config-push
# sequence -- so unlike LFCPNXPCIEPHY there is no LMMI_app.v/lmmi_fixup FSM here at all;
# usr_lmmi_*/ucfg_* are simply tied off, matching the tie-off wiring Lattice's own
# eval_pcie.v reference design uses when the runtime CSR/config-space access path isn't
# needed (aux_clk_i tied to 1'b0 is likewise taken directly from that reference design).
#
# clk_usr_i needs a real external clock, minimum frequency set by the link speed baked
# into the archive at generation time (per the IP's own port comment: "Min. Clock input,
# 62.5 MHz - Gen1, 125MHz - Gen2, 250MHz - Gen3"); the default archive in ip_urls below
# was generated for a Gen1 (2.5GT/s) link, so >=62.5MHz on "clkin_usr" is required.
#
# The "pcie" domain and usr_lmmi_clk_i are clocked directly from clkin_usr, never from the IP's
# clk_usr_o (left open): with usr_lmmi_clk_i fed back from clk_usr_o, the IP doesn't come up and
# the device doesn't enumerate (seen on hardware). Lattice's reference design likewise clocks
# LMMI from a free-running clock.

import os
import subprocess

from migen import *

from litex.gen import *

from litex.soc.interconnect.csr import *

from litepcie.common import *
from litepcie.tlp.common import *
from litepcie.phy.common import *

# LFD2NXPCIEPHY --------------------------------------------------------------------------------

class LFD2NXPCIEPHY(LiteXModule):
    endianness    = "big"
    qword_aligned = False

    def __init__(self, platform, pads, data_width=64, pcie_data_width=32, cd="pcie", bar0_size=65536):
        # Streams ---------------------------------------------------------------------------------
        self.sink   = stream.Endpoint(phy_layout(data_width))
        self.source = stream.Endpoint(phy_layout(data_width))
        # FIXME: Connect (as with LFCPNXPCIEPHY: this generated IP has no explicit MSI request/ack
        # pins either, only legacy_interrupt_i/o -- tied off below, see do_finalize()'s Instance).
        self.msi    = stream.Endpoint(msi_layout())

        # Registers --------------------------------------------------------------------------------
        self._link_status = CSRStatus(fields=[
            CSRField("status", size=1, values=[
                ("``0b0``", "Link Down."),
                ("``0b1``", "Link Up."),
            ]),
        ])

        # Parameters/Locals ------------------------------------------------------------------------
        self.platform   = platform
        self.perst_n_i  = pads.perst
        self.data_width = data_width
        self.pcie_data_width = pcie_data_width
        self.id         = Signal(16, reset_less=True)
        self.bar0_size  = bar0_size
        self.bar0_mask  = get_bar_mask(bar0_size)

        self.max_request_size = Signal(16, reset=128) # FIXME.
        self.max_payload_size = Signal(16, reset=128) # FIXME.

        # # #

        # This IP is only ever generated single-lane; pcie_data_width is fixed at 32-bit
        # (vc_tx_data_i/vc_rx_data_o), independent of the LitePCIe-side data_width
        # (converted via PHYTXDatapath/PHYRXDatapath).
        assert data_width in [64, 128]
        assert pcie_data_width == 32, "pcie_data_width must be 32 (this IP is generated single-lane only)."

        # Clocking / Reset -------------------------------------------------------------------------
        clk_usr_i = platform.request("clkin_usr")
        self.cd_pcie = ClockDomain()
        self.comb += self.cd_pcie.clk.eq(clk_usr_i)

        # Link Status ------------------------------------------------------------------------------
        link_up    = Signal()
        pl_link_up = Signal()
        dl_link_up = Signal()
        tl_link_up = Signal()
        self.comb += [
            link_up.eq(pl_link_up & dl_link_up & tl_link_up),
            self._link_status.fields.status.eq(link_up),
        ]

        # TX (FPGA --> HOST) CDC / Data Width Conversion -------------------------------------------
        tx_data_p = Signal(pcie_data_width//8)
        self.tx_datapath = PHYTXDatapath(
            core_data_width = data_width,
            pcie_data_width = pcie_data_width,
            clock_domain    = cd,
        )
        self.comb += self.sink.connect(self.tx_datapath.sink, omit={"dat", "be"})
        self.comb += dword_endianness_swap(
            src        = self.sink.dat,
            dst        = self.tx_datapath.sink.dat,
            data_width = data_width,
            endianness = "big",
            mode       = "dat",
        )
        self.comb += dword_endianness_swap(
            src        = self.sink.be,
            dst        = self.tx_datapath.sink.be,
            data_width = data_width,
            endianness = "big",
            mode       = "be",
        )
        # vc_tx_* has no byte enables: drop the padding DWORDs of odd-length TLPs.
        self.tx_padding = tx_padding = ClockDomainsRenamer("pcie")(PHYTXPaddingRemover(pcie_data_width))
        self.comb += self.tx_datapath.source.connect(tx_padding.sink)
        self.s_axis_tx = s_axis_tx = tx_padding.source

        for i in range(pcie_data_width//8):
            self.comb += tx_data_p[i].eq(Reduce("XOR", self.s_axis_tx.dat[i*8:(i+1)*8]))

        # RX (HOST --> FPGA) CDC / Data Width Conversion -------------------------------------------
        self.rx_datapath = PHYRXDatapath(
            core_data_width = data_width,
            pcie_data_width = pcie_data_width,
            clock_domain    = cd,
        )
        rx_sop = Signal()
        # vc_rx_* has no byte enables: pad odd-length TLPs with be == 0 DWORDs before up-conversion.
        self.rx_padding = rx_padding = ClockDomainsRenamer("pcie")(PHYRXPaddingInserter(pcie_data_width, ratio=data_width//pcie_data_width))
        self.comb += rx_padding.source.connect(self.rx_datapath.sink)
        self.m_axis_rx = m_axis_rx = rx_padding.sink
        self.comb += [
            m_axis_rx.first.eq(rx_sop),
            m_axis_rx.be.eq(2**len(m_axis_rx.be) - 1),
        ]
        self.comb += self.rx_datapath.source.connect(self.source, omit={"dat", "be"})
        self.comb += dword_endianness_swap(
            src        = self.rx_datapath.source.dat,
            dst        = self.source.dat,
            data_width = data_width,
            endianness = "big",
            mode       = "dat",
        )
        self.comb += dword_endianness_swap(
            src        = self.rx_datapath.source.be, # FIXME: Should be adapted.
            dst        = self.source.be,
            data_width = data_width,
            endianness = "big",
            mode       = "be",
        )

        # PCIe hard IP -----------------------------------------------------------------------------
        self.ip_params = dict()
        self.ip_params.update(
            # Serial / Ref Clk ------------------------------------------------------------------
            i_refclkp_i                   = pads.clk_p,
            i_refclkn_i                   = pads.clk_n,
            i_refret_i                    = pads.refret,
            i_rext_i                      = pads.rext,
            i_aux_clk_i                   = Constant(0, 1), # Tied 0 in Lattice's own eval_pcie.v.

            # TX/RX Serial ------------------------------------------------------------------------
            o_txp_o                       = pads.tx_p,
            o_txn_o                       = pads.tx_n,
            i_rxp_i                       = pads.rx_p,
            i_rxn_i                       = pads.rx_n,

            # Clk/Rst ---------------------------------------------------------------------------
            i_perst_n_i                   = pads.perst,
            # No boot config-push to gate on (unlike LFCPNXPCIEPHY's config_done): this IP's
            # config-space parameters are baked in at IP-generation time (see module header).
            i_rst_usr_n_i                 = pads.perst,
            i_clk_usr_i                   = clk_usr_i,
            o_clk_usr_o                   = Open(), # Not used as a clock: see module header.
            o_u_pl_link_up_o              = pl_link_up,
            o_u_dl_link_up_o              = dl_link_up,
            o_u_tl_link_up_o              = tl_link_up,

            i_user_aux_power_detected_i   = Constant(0, 1),
            i_user_transactions_pending_i = Constant(0, 1),

            # Raw PCIe Config-Space Access (ucfg) -- unused, tied off per eval_pcie.v -------------
            i_ucfg_valid_i                = Constant(0, 1),
            i_ucfg_wr_rd_n_i              = Constant(0, 1),
            i_ucfg_addr_i                 = Constant(0, 10),
            i_ucfg_f_i                    = Constant(0, 3),
            i_ucfg_wr_be_i                = Constant(0, 4),
            i_ucfg_wr_data_i              = Constant(0, 32),
            o_ucfg_rd_data_o              = Open(32),
            o_ucfg_rd_done_o              = Open(),
            o_ucfg_ready_o                = Open(),

            # LMMI (Configuration) -- unused, tied off: this IP bakes vendor/device ID, BAR
            # sizing and MSI capability into synthesis-time parameters instead. -----------------
            i_usr_lmmi_clk_i              = clk_usr_i, # Free-running: must run before the IP is up.
            i_usr_lmmi_resetn_i           = Constant(1, 1),
            i_usr_lmmi_request_i          = Constant(0, 1),
            i_usr_lmmi_wr_rdn_i           = Constant(1, 1),
            i_usr_lmmi_wdata_i            = Constant(0, 32),
            i_usr_lmmi_offset_i           = Constant(0, 15),
            o_usr_lmmi_rdata_o            = Open(32),
            o_usr_lmmi_rdata_valid_o      = Open(),
            o_usr_lmmi_ready_o            = Open(),

            # TLP Receive Interface (HOST --> FPGA) ------------------------------------------------
            i_vc_rx_ready_i               = m_axis_rx.ready,
            o_vc_rx_valid_o               = m_axis_rx.valid,
            o_vc_rx_sel_o                 = Open(2),
            o_vc_rx_cmd_data_o            = Open(13),
            o_vc_rx_sop_o                 = rx_sop,
            o_vc_rx_data_o                = m_axis_rx.dat,
            o_vc_rx_datap_o               = Open(4),
            o_vc_rx_eop_o                 = m_axis_rx.last,
            o_vc_rx_err_ecrc_o            = Open(),
            o_vc_rx_f_o                   = Open(2),

            i_vc_rx_credit_init_i         = Constant(1, 1),
            i_vc_rx_credit_nh_i           = Constant(0, 12),
            i_vc_rx_credit_nh_inf_i       = Constant(1, 1),
            i_vc_rx_credit_return_i       = Constant(1, 1),

            # TLP Transmit Interface (FPGA --> HOST) ------------------------------------------------
            i_vc_tx_valid_i               = s_axis_tx.valid,
            i_vc_tx_eop_i                 = s_axis_tx.last,
            i_vc_tx_eop_n_i               = Constant(0, 1),
            i_vc_tx_sop_i                 = s_axis_tx.first, # CHECKME/FIXME: Verify it's generated by LitePCIe.
            i_vc_tx_data_i                = s_axis_tx.dat,
            i_vc_tx_datap_i               = tx_data_p,
            o_vc_tx_ready_o               = s_axis_tx.ready,

            o_vc_tx_credit_init_o         = Open(),
            o_vc_tx_credit_return_o       = Open(),
            o_vc_tx_credit_nh_o           = Open(12),

            # Legacy Interrupt -- not driven: MSI isn't wired up for this PHY either (see
            # self.msi above); tie the request input idle. --------------------------------------
            i_legacy_interrupt_i          = Constant(0, 1),
            o_legacy_interrupt_o          = Open(),
        )

    # Finalize -------------------------------------------------------------------------------------

    # Radiant IPGen-generated IP archive (single-lane only; see module header).
    ip_urls = {
        1: "https://www.firmwaredesign.no/litepcie/lattice/lfd2nx-pcie-1x/pci.zip",
    }

    def do_finalize(self):
        nlanes = 1 # This IP is only ever generated single-lane (module="pcie_x1").
        assert nlanes in self.ip_urls, f"No pci IP archive available for phy_lanes={nlanes}."
        url = self.ip_urls[nlanes]

        cache_name = f"lfd2nxpciephy_x{nlanes}"
        cache_dir  = os.path.join(self.platform.output_dir, cache_name)
        src_zip    = os.path.join(self.platform.output_dir, f"{cache_name}.zip")
        src_dir    = os.path.join(cache_dir, "pci") # Zip's own top-level folder.
        if not os.path.exists(src_dir):
            # If zip archive is not available
            if not os.path.exists(src_zip):
                # Download archive.
                # Build the wget command
                command = ["wget", "-O" , src_zip, url]
                try:
                    print(f"Downloading {url}...")
                    # Execute the wget command
                    result = subprocess.run(command, check=True)
                    print(f"Downloaded {src_zip} successfully!")
                except subprocess.CalledProcessError as e:
                    print(f"Failed to download {url}. Error: {e}")
                except FileNotFoundError:
                    print("The 'wget' command is not available. Please install wget and try again.")

            # Extract archive.
            os.makedirs(cache_dir, exist_ok=True)
            command = ["unzip", src_zip, "-d" , cache_dir]
            try:
                print(f"Unzipping {src_zip}...")
                # Execute the wget command
                result = subprocess.run(command, check=True)
                print(f"Unzipped {src_zip} successfully!")
            except subprocess.CalledProcessError as e:
                print(f"Failed to unzip {src_zip}. Error: {e}")
            except FileNotFoundError:
                print("The 'unzip' command is not available. Please install unzip and try again.")

        self.platform.add_source(os.path.join(src_dir, "rtl", "pci.v"))

        self.specials += [
            Instance("pci", **self.ip_params),
            Instance("GSR",
                i_CLK   = ClockSignal("pcie"),
                i_GSR_N = self.perst_n_i,
            )
        ]
